/*
 * This source file was generated by the Gradle 'init' task
 */
package gradle_project;

import controllers.RequestController;
import io.javalin.Javalin;
import static io.javalin.apibuilder.ApiBuilder.*;

public class App {
    //COMENTARIO
    public void starApp(){
        Javalin app = Javalin.create(config -> {
            config.router.apiBuilder(() -> {
                path("users", () -> {
                    get(RequestController::getAll);
                    post(RequestController::sendData);
                });
            });
        }).start(80);
    }

    public static void main(String[] args) {
        new App().starApp();
    }
}
